services:
  backend:
    build: ./backend
    container_name: bun-backend
    ports:
      - "3000:3000"

  frontend:
    build: ./frontend
    container_name: angular-frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend


